-- Database: mutu

CREATE TABLE IF NOT EXISTS akreditasi (
  id TINYINT PRIMARY KEY,
  paripurna DECIMAL(5,2) NOT NULL DEFAULT 0,
  utama DECIMAL(5,2) NOT NULL DEFAULT 0,
  madya DECIMAL(5,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO akreditasi (id, paripurna, utama, madya) VALUES (1, 45.00, 35.00, 20.00)
  ON DUPLICATE KEY UPDATE paripurna=VALUES(paripurna), utama=VALUES(utama), madya=VALUES(madya);

-- Per-region akreditasi (per kabupaten/kota, per bulan+tahun)
CREATE TABLE IF NOT EXISTS akreditasi_regions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  year INT NOT NULL,
  month INT NOT NULL,
  region VARCHAR(100) NOT NULL,
  paripurna DECIMAL(5,2) NOT NULL DEFAULT 0,
  utama DECIMAL(5,2) NOT NULL DEFAULT 0,
  madya DECIMAL(5,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_region_period (year, month, region)
);

CREATE TABLE IF NOT EXISTS indikators (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  region VARCHAR(100) DEFAULT NULL,
  capaian DECIMAL(5,2) NOT NULL DEFAULT 0,
  target DECIMAL(5,2) NOT NULL DEFAULT 100,
  status ENUM('Mencapai Target','Tidak Mencapai Target') NOT NULL DEFAULT 'Tidak Mencapai Target',
  `date` DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  file_url VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  instansi VARCHAR(50) DEFAULT NULL,
  photo_url VARCHAR(1024) DEFAULT NULL,
  role ENUM('admin','member') NOT NULL DEFAULT 'member',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  token CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (user_id),
  CONSTRAINT fk_auth_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
